### ISSUE TITLE
Assignment 1-1 - The Basics

### ISSUE THREAD

**Issue by gstark** [chadoak4/assignments#1]
- [x] Read Mason's [Code School Manefesto](http://masondesu.github.io/code-school-manifesto/).
- [x] Look over this [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). You don't need to commit it all to memory. You probably won't understand all of it; that's okay. Just skim it, know that it exists, bookmark it, and refer to it often as we move forward.
- [x] Complete the just the exercises given below by copying the comments to a new file (name it `day_one.rb`) and placing your solution below each comment.
- [x] Publish your completed exercises to a Github Gist
  - HINT: Use the same filename in the "Filename with extension" input box.
- [x] Add the link to the Github Gist to a comment in this issue
- [x] Close the issue to indicate you are complete
- **Bonus**
  - [x] Clone the Gist you created to your computer.
  - [x] Add the bonus exercises to your `day_one.rb` and attempt to complete them both.
  - [x] Install `zsh` and `oh-my-zsh` and choose a theme of your liking. Take a screenshot of your terminal with the theme installed. Attach to the issue before closing.
  - [x] Customize the color of your terminal background and font color. Take a screenshot of your terminal with your color selection. Attach to the issue before closing.
- [x] Close this issue to notify me for review.

`day_one.rb`:

``` ruby
#1. Assign "Hello World" to a variable named message.

#2. Assign a different string to a different variable.

#3. Assign a number to a variable.

#4. Make an array of at least four of your favorite movies or books or bands.

#5. Make a hash of information about yourself with at least four key-value pairs.
```
### Bonus Exercises

``` ruby
#6. Use string interpolation to display the number from exercise 3 in the middle a string.

#7. Make an array of hashes containing more information about your favorite movies. The hashes should have at least three key value pairs.

#8. Use `each` to loop through the answer from exercise #7 and print only one property from the hash. i.e., given `{ title: "Gone with the Wind" }` you print "Gone with the Wind".
```
### Resources
- Creating gists - https://help.github.com/articles/creating-gists/
- Try out your code first in `irb`
- Ask questions. Talk to other students first, then come ask in pairs!

**Comment by chadoak4** [comment]
https://gist.github.com/chadoak4/278d5628c75fb0ebb060

**Comment by chadoak4** [comment]
close

**Comment by gstark** [comment]
Good job! Number 1 and 4 need a little work. See if you can figure out what parts need improvement on each of these. For some of these try running them in irb

**Comment by chadoak4** [comment]
close. I believe I corrected the issues. Variable can't contain a capital like I had and quotation marks were missing from #4.

**Comment by chadoak4** [comment]
<img width="554" alt="screen shot 2015-08-25 at 1 34 23 am" src="https://cloud.githubusercontent.com/assets/13710769/9459440/8f8b2bc8-4ac9-11e5-8aa4-e42fde19656f.png">

**Comment by gstark** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/TeBpzQZRaBIC4/200w_d.gif)
