### ISSUE TITLE
Assignment 5-1 - Green Eggs and Ham

### ISSUE THREAD

**Issue by gstark** [chadoak4/assignments#16]
## Enumerable Practice

This assignment practices what we learned about `Enumerable` -- We continue to use various `enumerable` methods such as `all?` and `any?` in our recent homework. This practice reinforces some of the other enumerables available to us.

_Explorer Mode_
- Go to this URL https://github.com/tiy-tpa-ruby-q3-2015/green_eggs_and_ham
- [x] _Fork_ the repo using the github web ui (click on the FORK icon in the upper right)
- [x] _clone_ the repository to your computer. Ensure you are in the main directory where you keep your various projects (e.g. `~/tiy`) and are _NOT_ inside another homework assignment's directory.
- [x] Follow the directions in the readme (which you can see on the github page as well)

_Adventure Mode_
- [x] Write a test to validate how many punctuation marks are in the text. Write the _TEST_ into the test_green_eggs_and_ham.rb _first_ -- you will have to manually count the punctuation. Then write a test to expect that as the result of a method called `punctuation_count` defined in the class in `green_eggs_and_ham.rb`
- [ ] Write a test to validate the line that is in the file the most often. (excluding blanks) -- Figure out _yourself_ which line this is. Then write a test to expect that as the result of a method called `punctuation_count` defined in the class in `green_eggs_and_ham.rb`

**Comment by chadoak4** [comment]
Will try to get to last one today, but am closing in case I do not. 

https://github.com/chadoak4/green_eggs_and_ham

**Comment by gstark** [comment]
With code like:

```
def story_words
    @text.split.map { |word| word.downcase.gsub(/[^a-z-]/, "" ) }
    p @text.split.map { |word| word.downcase.gsub(/[^a-z-]/, "" ) }
  end
```

you really only need:

```
def story_words
    p @text.split.map { |word| word.downcase.gsub(/[^a-z-]/, "" ) }
  end
```

since `p` returns the value on the right. This makes it handy for cases like this.

in `number_of_words_shorter_than` you should use `x` instead of the hardcoded `4` in the method body.

in `lines` you can write `lines_wo_space = num_lines.reject { |x| x == "" }` which has the benefit of _not_ modifying the `num_lines` variable. Given an enumerable that modifies in place versus one that does not, typically we want to prefer the one that does not. This isn't a hard rule, but a preference when deciding between two methods.

All minor issues.

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/4sedXvfhLfusE/200w_d.gif)

**Comment by chadoak4** [comment]
Thank you for the feedback. I will look into this.
