### ISSUE TITLE
Assignment 5-2 - Databasics

### ISSUE THREAD

**Issue by gstark** [chadoak4/assignments#17]
Fork the repository below and follow the instructions in the included README.md

[https://github.com/tiy-tpa-ruby-q3-2015/databasics](https://github.com/tiy-tpa-ruby-q3-2015/databasics)

**Comment by chadoak4** [comment]
https://github.com/chadoak4/databasics/blob/master/README.md

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/5taxY6RP1AHmM/200w_d.gif)
