### ISSUE TITLE
Assignment 8-1 - Continue Iron Topics

### ISSUE THREAD

**Issue by gstark** [chadoak4/assignments#28]
Complete Iron Topics while looking at the in-class code from week8/day-1

Close this issue when you have closed the weekend lab issue.

**Comment by chadoak4** [comment]
https://github.com/chadoak4/rubytopics

https://irontopics.herokuapp.com/ - png files are not loading to heroku

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/o7H9mn7R9SIIE/200w_d.gif)
