### ISSUE TITLE
Assignment 2-3 - Octodex

### ISSUE THREAD

**Issue by gstark** [chadoak4/assignments#7]
### Description

GitHub has a great mascot called OctoCat. OctoCat even has it's own gallery of variations, created by GitHub itself and fans, called [Octodex](https://octodex.github.com).

Unfortunately, the Octodex is not responsive*! Today, your task is to recreate the layout of The Octodex as closely as possible, but make it responsive. You can use all the tools you have at your disposal to get the job done. Use your browser's Developer Tools to inspect their site to find the exact font sizes and padding amounts.

![](https://dl.dropboxusercontent.com/u/4024808/tiy/octodex.png)
- Well, it turns out it uses javascript set the number of columns on page load, but we want to see interactive responsiveness when we resize our window!
### Objectives
- Understand HTML/CSS Layout
- Be able to place any element on a page where you want it.
- Use responsive design techniques to adapt a design to different screen sizes.
### Deliverables
- [ ] a git repo containing:
  - [ ] `index.html`
  - [ ] `styles` folder
    - [ ] `style.css`
  - [ ] `images` folder
    - [ ] with any images you used with your design
- [ ] a working, publicly visible website with a public URL (i.e. on Github pages).
## Explorer Mode

Create the page as closely as you possibly can. Use the same fonts, sizes colors. Download some of your favorite Octocat images to use in your page.
## Adventure Mode

If you're feeling adventurous, use a CSS framework like Bootstrap or Skeleton to layout your page. This will be both easier and harder. :trollface:
## Additional Resources
- http://getbootstrap.com
- http://getskeleton.com
- http://google.com/fonts
- [Learn CSS Layout](http://learnlayout.com/)
- [CSS Triangle Generator](http://apps.eky.hk/css-triangle-generator/)

**Comment by chadoak4** [comment]
https://github.com/chadoak4/octodex/tree/master/tiy/octocats

**Comment by gstark** [comment]
Come see me about this assignment. I remember we had trouble with git so I want to make sure I am reviewing the correct html+css.

**Comment by chadoak4** [comment]
I read your email this morning and created a new repository : pages : http://chadoak4.github.io/octocats/ code: https://github.com/chadoak4/octocats/tree/master. Yet, I still need to delete the old repository and am afraid if I delete it, I will lose everything in my new repository.

**Comment by gstark** [comment]
Good stuff!

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/5fBH6zrcIiOs65zXCtG/200w_d.gif)
